
name: Non OMV test scripts

on:
  push:
    branches: [ master, development, experimental, test* ]
  pull_request:
    branches: [ master, development, experimental, test* ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Install OMV
      run: |
        pip install git+https://github.com/OpenSourceBrain/osb-model-validation 

        #pip install 'numpy<=1.23.0' # see https://github.com/OpenSourceBrain/osb-model-validation/issues/91

    - name: Test some scripts
      run: |
        pip install pyneuroml
        omv install PyNN
        ./regenerate.sh

    - name: OMV final version info
      run: |
        omv list -V # list installed engines
        env
